apiVersion: velero.io/v1
kind: Restore
metadata:
  name: hcp-osp-restore
  namespace: openshift-adp
spec:
  includedNamespaces:
  - clusters
  - clusters-example-hosted
  backupName: hcp-osp-backup
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: hcp-osp-backup
  veleroCredentialsBackupName: hcp-osp-backup
  veleroResourcesBackupName: hcp-osp-backup
  restorePVs: true
  preserveNodePorts: true
  existingResourcePolicy: update
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
